project_id = "pkejvzexmlijnoangerw"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.og-product]
verify_jwt = false

[functions.og-dog]
verify_jwt = false
